server.port=9090
spring.application.name=demo

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/sdn_db
spring.datasource.username=postgres
spring.datasource.password=info_123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka Broker (Your Laptop)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=security-platform
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust your target package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.demo.kafka.event

# Map incoming JSON directly to your consumer model class
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.demo.kafka.event.TrafficEvent
# Friend's OpenDaylight (Lighty.io) RESTCONF Base URL
opendaylight.url=http://10.199.97.63:8082/api/v1/network/traffic
opendaylight.username=admin
opendaylight.password=admin


# JWT secret must be at least 32 characters (256 bits) for HS256.
# Generate a real one for production ? never commit a real secret to git.
jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS
jwt.expiration-ms=86400000
# 86400000 ms = 24 hours

# Once you add spring-boot-starter-mail for real reset emails:
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=kumaripoojasah@gmail.com
# spring.mail.password=123
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
