package com.example.demo.dto.traffic;

import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;
import java.util.Arrays;

@Getter
@Builder
public class TrafficResponse {

    private String deviceId;
    // Changed to String to match "device-1", "device-2" etc.
    private String deviceName;
    private String sourceIp;
    private String destinationIp;
    private LocalDateTime timestamp;

    private Long packetCount;
    private Long byteCount;
    private Double packetRate;
    private Double byteRate;
    private Double activeFlows;
    private Double forwardPacketRate;
    private Double backwardPacketRate;
    private Double packetLengthStdDev;
    private Integer tcpFlagSynCount;
    private Integer tcpFlagAckCount;
    private Double interArrivalTimeMs;
    private Integer uniqueSources;
    private Integer uniquePorts;   // Added if you need unique ports
    private String protocol;
    // Derived/Engineered Features to show on UI
    private Double synToAckRatio;
    private Boolean isHighVolume;
    private double[] featureVector; // The full array generated by toFeatureVector()
}